### ISSUE TITLE
OpenRA TD HD Winter Tile-Set tree's with snow on them

### ISSUE THREAD

**Issue by JMegaTank** [pchote/TiberianDawnHD#17]
Please could someone fix the Winter tile-set with the tree's covered in snow it would be much appreciated and I know it has them in the Remasters and would be awesome if it was in OpenRA TD HD mod to.
the tree's with the snow on them look beautiful and the Winter tile-set is unique to Tiberian Dawn.

Many Thanks

J MegaTank
![Screenshot (1)](https://user-images.githubusercontent.com/51249762/217327229-cb2da1ff-b858-41a7-8ea7-cc9a6a4ce5a1.png)

**Comment by pchote** [comment]
Fixed by 579154e691fc36fc46cac49ff3f30c2783d56ace.
