### ISSUE TITLE
Artillery Wreck is Bike

### ISSUE THREAD

**Issue by Orb370** [pchote/TiberianDawnHD#18]
Title
![2023-02-18 18_30_33-OpenRA - Tiberian Dawn](https://user-images.githubusercontent.com/42915475/219905560-812534aa-5f83-43f3-8310-9dc00dceb5e3.png)

**Comment by pchote** [comment]
Fixed by b26d75bcac6f92f5fbcad8dd2082f4c65562bc4d.
