### ISSUE TITLE
Unable to find the game files on Linux

### ISSUE THREAD

**Issue by hazelnot** [pchote/TiberianDawnHD#2]
I downloaded and ran the appimage, but on startup OpenRA displays the Install Content prompt, with the text: "Tiberian Dawn requires artwork and audio from the C&C Remastered Collection. Please purchase and install the collection through Steam or Origin and try again." The only option is to quit the game.

I do have the Remastered Collection installed through Steam, but OpenRA seems to be unable to detect it.

**Comment by yuri-ccp** [comment]
Yep, need a guide of how to install in non-windows OSs

**Comment by pchote** [comment]
@hazelnot: [playtest-20221224](https://github.com/pchote/TiberianDawnHD/releases/tag/playtest-20221224) now uses https://github.com/OpenRA/OpenRA/pull/20439, which has some changes to (hopefully) improve compatibility. If it still doesn't work, please file an issue against [OpenRA/OpenRA](https://github.com/OpenRA/OpenRA/)!

@yuri-ccp: I have added some instructions to the repository readme.
