### ISSUE TITLE
Tree Type: 8  A lot bigger then it used to be

### ISSUE THREAD

**Issue by JMegaTank** [pchote/TiberianDawnHD#22]
Have noticed in the Remasters they have made Tree Type: 08 a lot bigger then it used to be
if you look on the OpenRA and Original C&C version they both had the smaller tree
Remasters have made it bigger making it look strange on some maps in certain map placements and positions. 
one for the map makers and I hope its a easy fix.

![OpenRA_Tree_type_8](https://user-images.githubusercontent.com/51249762/219965593-9a16caed-1e2a-41ed-8590-6e5b1eac6df3.png)
![Tree_type_8](https://user-images.githubusercontent.com/51249762/219965599-d2ca0a18-820a-4a78-8b18-65793b74fee2.png)
![OpenRA_TD_HD_Tree_type_8](https://user-images.githubusercontent.com/51249762/219965607-e20019f0-aba2-4986-801b-dd5046de6177.png)

**Comment by pchote** [comment]
Fixed by 4cb431ece44778390c908317e9a6a1cf80f121d3.
