### ISSUE TITLE
Docking animation of harvester is still showing the old graphics

### ISSUE THREAD

**Issue by jdelange22** [pchote/TiberianDawnHD#3]
When a harvester is docking the refinery the docking animation still shows the old non-remasterd graphics. Whenever the havester is ready to release the graphics return to normal remasterd graphics when the harvester rides away. This only applies to the harvester. The refinery itself isn't affected by this issue.

**Comment by pchote** [comment]
Depends on upstream support for load-time masking of sprites, which hasn't yet been implemented.

**Comment by pchote** [comment]
Fixed by d209d13cb6596f48419712bb42a27dfad5f958c6.
