### ISSUE TITLE
Ion cannon animation is offset from impact area

### ISSUE THREAD

**Issue by dragunoff** [pchote/TiberianDawnHD#6]
It appears as though the cannon is striking a few cells south of the target. Tested on playtest-20221224.

https://user-images.githubusercontent.com/1355810/210108875-fae3efbd-763d-44f9-b3dd-e48370df7489.mp4

**Comment by pchote** [comment]
Fixed by dba79f552118b4a81b0f2036ab82a7f7e1bcdb65.
